package com.expensetracker.model;

public class Income {

    private int id;
    private String date;
    private String category;
    private String description;
    private double amount;

    /* ============================
       CONSTRUCTORS
       ============================ */

    // Constructor for DB retrieval (all fields)
    public Income(int id, String date, String category, String description, double amount) {
        this.id = id;
        this.date = safe(date);
        this.category = safe(category);
        this.description = safe(description);
        this.amount = amount;
    }

    // Constructor for new expense (id auto-generated by DB)
    public Income(String date, String category, String description, double amount) {
        this.date = safe(date);
        this.category = safe(category);
        this.description = safe(description);
        this.amount = amount;
    }

    /* ============================
       GETTERS & SETTERS
       ============================ */

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getDate() { return date; }
    public void setDate(String date) {
        this.date = safe(date);
    }

    public String getCategory() { return category; }
    public void setCategory(String category) {
        this.category = safe(category);
    }

    public String getDescription() { return description; }
    public void setDescription(String description) {
        this.description = safe(description);
    }

    public double getAmount() { return amount; }
    public void setAmount(double amount) {
        this.amount = amount;
    }

    /* ============================
       HELPER
       ============================ */
    private String safe(String value) {
        return (value == null) ? "" : value.trim();
    }

    /* ============================
       TO STRING
       ============================ */
    @Override
    public String toString() {
        return String.format(
                "%s | %s | %s | %.2f",
                (date == null ? "" : date),
                (category == null ? "" : category),
                (description == null ? "" : description),
                amount
        );
    }
}
